# Generated by Django 3.2.8 on 2021-10-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computer',
            table='computers',
        ),
    ]
