# Generated by Django 3.2.8 on 2021-10-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20211029_1347'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avatarmodel',
            table='avatars',
        ),
    ]
