# Generated by Django 3.2.8 on 2021-10-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_avatarmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatarmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ('id',)},
        ),
    ]
