const LOAD_GENRES = 'LOAD_GENRE';
const LOAD_GENRE_MOVIE_PAGE = 'LOAD_GENRE_MOVIE_PAGE';
const LOAD_MIX_MOVIE_PAGE = 'LOAD_GLOBAL_MOVIE_PAGE';
const LOAD_TOP_MOVIE_PAGE = 'LOAD_TOP_MOVIE_PAGE';
const LOAD_SOON_MOVIE_PAGE = 'LOAD_SOON_MOVIE_PAGE';

export {LOAD_GENRES, LOAD_MIX_MOVIE_PAGE, LOAD_GENRE_MOVIE_PAGE, LOAD_TOP_MOVIE_PAGE,LOAD_SOON_MOVIE_PAGE}

