# Generated by Django 3.2.9 on 2021-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_driver',
            field=models.BooleanField(),
        ),
    ]
