const LOAD_GENRES = 'LOAD_GENRE';
const LOAD_GENRE_MOVIE_PAGE = 'LOAD_GENRE_MOVIE_PAGE';
const LOAD_MIX_MOVIE_PAGE = 'LOAD_MIX_MOVIE_PAGE';
const LOAD_TOP_MOVIE_PAGE = 'LOAD_TOP_MOVIE_PAGE';
const LOAD_SOON_MOVIE_PAGE = 'LOAD_SOON_MOVIE_PAGE';
const LOAD_MOVIE_INFO = 'LOAD_MOVIE_INFO';
const SET_TITLE_MOVIE_LIST = 'SET_TITLE_MOVIE_LIST';
const LOAD_TV_TOP_RATED = 'LOAD_TV_TOP_RATED'

export {LOAD_GENRES, LOAD_MIX_MOVIE_PAGE, LOAD_GENRE_MOVIE_PAGE, LOAD_TOP_MOVIE_PAGE,LOAD_SOON_MOVIE_PAGE, LOAD_MOVIE_INFO,SET_TITLE_MOVIE_LIST,
    LOAD_TV_TOP_RATED}

